brand_name: "SilicoPharm, Inc."
brand_logo: /assets/img/branding/sp_logo_resized.png
brand_logo_symbol: /assets/img/branding/sp_logo_symbol_resized.png
cta_label: "Try KnockG"
cta_url: "https://www.knockg.com"
channeltalk_plugin_key: "d0e8dc75-ef8e-46db-a7e5-ea87be6c0006"
